refresh_data:
  name: Refresh data
  description: Refresh vehicle data
  fields:
    vin:
      name: Device
      description: your vehicle
      required: true
      selector:
        device:
          integration: audiconnect

turn_on_action:
  name: Turn on
  description: Turn on action
  fields:
    vin:
      name: Device
      description: Set VIN code
      required: true
      selector:
        device:
          integration: audiconnect  
    action:
      required: true
      description: service
      name: Action
      selector:
        select:
          translation_key: select_mode
          options:
            - lock
            - climater
            - charger
            - pre_heating
            - window_heating
            - ventilation

turn_off_action:
  name: Turn off
  description: Turn off action
  fields:
    vin:
      name: Device
      description: Set VIN code
      required: true
      selector:
        device:
          integration: audiconnect  
    action:
      required: true
      description: service
      name: Action
      selector:
        select:
          translation_key: select_mode
          options:
            - lock
            - climater
            - charger
            - pre_heating
            - window_heating
            - ventilation